// Refreshed from public World Cup 2026 Golden Boot markets on 2026-06-06
// (FanDuel, bet365, Covers/Kalshi, BetVictor). Keep values as plain display
// names because bonus scoring compares saved text.
export const topScorerCandidates = [
  "Kylian Mbappe",
  "Harry Kane",
  "Lionel Messi",
  "Erling Haaland",
  "Lamine Yamal",
  "Mikel Oyarzabal",
  "Cristiano Ronaldo",
  "Ousmane Dembele",
  "Lautaro Martinez",
  "Vinicius Junior",
  "Raphinha",
  "Julian Alvarez",
  "Ferran Torres",
  "Bukayo Saka",
  "Joao Pedro",
  "Luis Suarez",
  "Mikel Merino",
  "Richarlison",
  "Romelu Lukaku",
  "Nick Woltemade",
  "Michael Olise",
  "Kai Havertz",
  "Jude Bellingham",
  "Cole Palmer",
  "Rodrygo",
  "Neymar",
  "Goncalo Ramos",
  "Rafael Leao",
  "Bruno Fernandes",
  "Florian Wirtz",
  "Jamal Musiala",
  "Leroy Sane",
  "Serge Gnabry",
  "Cody Gakpo",
  "Memphis Depay",
  "Donyell Malen",
  "Noa Lang",
  "Xavi Simons",
  "Luis Diaz",
  "Jhon Duran",
  "Jhon Arias",
  "James Rodriguez",
  "Jonathan David",
  "Promise David",
  "Cyle Larin",
  "Christian Pulisic",
  "Ricardo Pepi",
  "Folarin Balogun",
  "Haji Wright",
  "Raul Jimenez",
  "Santiago Gimenez",
  "Hirving Lozano",
  "Orbelin Pineda",
  "Enner Valencia",
  "Antonio Sanabria",
  "Alexander Isak",
  "Viktor Gyokeres",
  "Dejan Kulusevski",
  "Kaoru Mitoma",
  "Takefusa Kubo",
  "Ayase Ueda",
  "Mohamed Salah",
  "Omar Marmoush",
  "Mostafa Mohamed",
  "Heung-min Son",
  "Lee Kang-in",
  "Mehdi Taremi",
  "Sardar Azmoun",
  "Lois Openda",
  "Kevin De Bruyne",
  "Breel Embolo",
  "Sadio Mane",
  "Nicolas Jackson",
  "Ismaila Sarr",
  "Youssef En-Nesyri",
  "Brahim Diaz",
  "Antoine Semenyo",
  "Mohammed Kudus",
  "Andre Ayew",
  "Andrej Kramaric",
  "Bruno Petkovic",
  "Darwin Nunez",
  "Federico Valverde",
  "Salem Al-Dawsari",
  "Sebastien Haller",
  "Simon Adingra",
  "Iqraam Rayners",
  "Alexander Sorloth",
  "Jorgen Strand Larsen",
  "Oscar Bobb",
] as const;
