// Seeded from public World Cup 2026 Golden Boot odds tables on 2026-05-25.
// Keep values as plain display names because bonus scoring compares saved text.
export const topScorerCandidates = [
  "Harry Kane",
  "Kylian Mbappe",
  "Lionel Messi",
  "Erling Haaland",
  "Lamine Yamal",
  "Vinicius Junior",
  "Cristiano Ronaldo",
  "Lautaro Martinez",
  "Ousmane Dembele",
  "Joao Pedro",
  "Estevao",
  "Romelu Lukaku",
  "Julian Alvarez",
  "Richarlison",
  "Bukayo Saka",
  "Kai Havertz",
  "Mohamed Salah",
  "Nick Woltemade",
  "Mikel Oyarzabal",
  "Ferran Torres",
  "Mikel Merino",
  "Michael Olise",
  "Jude Bellingham",
  "Cole Palmer",
  "Rodrygo",
  "Mateo Retegui",
  "Robert Lewandowski",
  "Lois Openda",
  "Raphinha",
  "Jean-Philippe Mateta",
  "Marcus Rashford",
  "Neymar",
  "Leroy Sane",
  "Serge Gnabry",
  "Enner Valencia",
  "Cody Gakpo",
  "Darwin Nunez",
  "Bruno Fernandes",
  "Memphis Depay",
  "Luis Diaz",
  "Marcus Thuram",
  "Kingsley Coman",
  "Randal Kolo Muani",
  "Anthony Gordon",
  "Desire Doue",
  "Jamal Musiala",
  "Dani Olmo",
  "Hugo Ekitike",
  "Kaoru Mitoma",
  "Goncalo Ramos",
  "Raul Jimenez",
  "Takefusa Kubo",
  "Rafael Leao",
  "Iqraam Rayners",
  "Antonio Sanabria",
  "Antoine Semenyo",
  "Luis Javier Suarez",
  "Phil Foden",
  "Omar Marmoush",
  "Nicolas Jackson",
  "Promise David",
  "Ricardo Pepi",
  "Rasmus Hojlund",
  "Pedri",
  "Noa Lang",
  "Morgan Rogers",
  "Armando Gonzalez",
  "Giacomo Raspadori",
  "Haji Wright",
  "Gabriel Martinelli",
  "Folarin Balogun",
  "Francesco Esposito",
  "Sadio Mane",
  "Florian Wirtz",
  "Donyell Malen",
  "Jonathan David",
  "Bradley Barcola",
  "Nico Williams",
  "Matheus Cunha",
  "Alexander Sorloth",
  "Pedro Neto",
  "Eberechi Eze",
  "Jhon Duran",
  "Heung-min Son",
  "Christian Pulisic",
  "Arda Guler",
  "Kenan Yildiz",
  "Breel Embolo",
  "Ayase Ueda",
  "Lee Kang-in",
  "James Rodriguez",
  "Brahim Diaz",
  "Andrej Kramaric",
  "Mehdi Taremi",
  "Jhon Arias",
  "Jorgen Strand Larsen",
  "Hirving Lozano",
  "Orbelin Pineda",
  "Oscar Bobb",
  "Youssef En-Nesyri",
] as const;
